### ISSUE TITLE
댓글 작성 API 리팩터링

### ISSUE THREAD

**Issue by yejin0718** [yejin0718/everyhanghae#51]
## Description

댓글 작성 API 리팩터링

## Before

-board와 comment의 id가 겹침
-ResponseDto Builder 사용
-Exception 메시지를 사용할때마다 작성해야함

## After

-board-id, comment-id로 변경하여 구별하기 쉽게 수정
-생성자가 많지 않아 빌더 패턴을 사용하지 않을 예정
-Exception 메시지 이넘으로 관리

## Todo

- [x] controller board-id, commen-id로 변경
- [x] ResponseDto에 빌더 제거
- [x] 엔티티 어노테이션 수정
- [x] Exception 메시지 이넘으로 관리
