### ISSUE TITLE
properties 파일 분리

### ISSUE THREAD

**Issue by seunGit** [yejin0718/everyhanghae#91]
## Description

properties 파일 분리

## Before

key 노출 문제로 properties 파일 분리.
JwtUtil key url 수정

## After

key 노출 방지, gitignore 내용 추가

## Todo

- [x] properties 파일 분리
- [x] gitignore 내용 추가
- [x] 분리된 key값 url 수정
